function createfigure2(X1, Y1)
%CREATEFIGURE2(X1, Y1, X2, Y2, X3, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 05-Apr-2017 16:35:27

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
set(axes1,'XGrid','on','XMinorTick','on','XScale','log','YGrid','on');
% Create semilogx
semilogx1 = semilogx(X1,Y1,'DisplayName','Niveau vs. f');

% Get xdata from plot for data statistics
xdata1 = get(semilogx1, 'xdata');
% Get ydata from plot for data statistics
ydata1 = get(semilogx1, 'ydata');
% Make sure data are column vectors
xdata1 = xdata1(:);
ydata1 = ydata1(:);


% Get axes ylim
axXLim1 = get(axes1,'xlim');

% Find the max
ymax1 = max(ydata1);
% Get coordinates for the max line
maxValue1 = [ymax1 ymax1];
% Plot the max
statLine1 = plot(axXLim1,maxValue1,'DisplayName','   y max','Tag','max y',...
    'Parent',axes1,...
    'LineStyle','-.',...
    'Color',[0 0 1]);

% Set new line in proper position
setLineOrder(axes1,statLine1,semilogx1);

% Create xlabel
xlabel('f(Hz)');

% Create title
title('Spectre pour fe=4000Hz');

% Create ylabel
ylabel('Niveau (dB)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.1 10000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-100 0]);
box(axes1,'on');
% Set the remaining axes properties
%set(axes1,'XGrid','on','XMinorTick','on','XScale','log','YGrid','on');
% Create legend
legend(axes1,'show');

%-------------------------------------------------------------------------%
function setLineOrder(axesh1, newLine1, associatedLine1)
%SETLINEORDER(AXESH1,NEWLINE1,ASSOCIATEDLINE1)
%  Set line order
%  AXESH1:  axes
%  NEWLINE1:  new line
%  ASSOCIATEDLINE1:  associated line

% Get the axes children
hChildren = get(axesh1,'Children');
% Remove the new line
hChildren(hChildren==newLine1) = [];
% Get the index to the associatedLine
lineIndex = find(hChildren==associatedLine1);
% Reorder lines so the new line appears with associated data
hNewChildren = [hChildren(1:lineIndex-1);newLine1;hChildren(lineIndex:end)];
% Set the children:
set(axesh1,'Children',hNewChildren);

