function createfigure1(f1, Niveau1,titre)
%CREATEFIGURE1(F1, NIVEAU1)
%  F1:  vector of x data
%  NIVEAU1:  vector of y data

%  Auto-generated by MATLAB on 05-Apr-2017 16:10:27

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
set(axes1,'XGrid','on','XMinorTick','on','XScale','log','YGrid','on');
% Create semilogx
semilogx1 = semilogx(f1,Niveau1,'DisplayName','Niveau vs. f');

% Get xdata from plot for data statistics
xdata1 = get(semilogx1, 'xdata');
% Get ydata from plot for data statistics
ydata1 = get(semilogx1, 'ydata');
% Make sure data are column vectors
xdata1 = xdata1(:);
ydata1 = ydata1(:);


% Get axes ylim
axYLim1 = get(axes1,'ylim');
% Get axes ylim
axXLim1 = get(axes1,'xlim');

indexMax=find(ydata1==max(ydata1));
% Find the max
xmax1 = xdata1(indexMax);%max(xdata1);
% Get coordinates for the max line
maxValue1 = [xmax1 xmax1];
% Plot the max
statLine1 = plot(maxValue1,axYLim1,'DisplayName',strcat('   f max = ',num2str(xmax1),' Hz'),'Tag','max x',...
    'Parent',axes1,...
    'LineStyle',':',...
    'Color',[0 0 0]);

% Set new line in proper position
setLineOrder(axes1,statLine1,semilogx1);

% Find the max
ymax1 = max(ydata1);
% Get coordinates for the max line
maxValue2 = [ymax1 ymax1];
% Plot the max
statLine2 = plot(axXLim1,maxValue2,'DisplayName',strcat('   Niveau max = ',num2str(ymax1),' dB'),'Tag','max y',...
    'Parent',axes1,...
    'LineStyle','--',...
    'Color',[1 0 0]);

% Set new line in proper position
setLineOrder(axes1,statLine2,semilogx1);

% Create xlabel
xlabel('f(Hz)');

% Create title
title(titre);

% Create ylabel
ylabel('Niveau (dB)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.899 101.00899]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-90 -20]);
box(axes1,'on');
% Set the remaining axes properties
%set(axes1,'XGrid','on','XMinorTick','on','XScale','log','YGrid','on');
% Create legend
legend(axes1,'show');
set(legend,'FontSize',11,'Location','best');

%-------------------------------------------------------------------------%
function setLineOrder(axesh1, newLine1, associatedLine1)
%SETLINEORDER(AXESH1,NEWLINE1,ASSOCIATEDLINE1)
%  Set line order
%  AXESH1:  axes
%  NEWLINE1:  new line
%  ASSOCIATEDLINE1:  associated line

% Get the axes children
hChildren = get(axesh1,'Children');
% Remove the new line
hChildren(hChildren==newLine1) = [];
% Get the index to the associatedLine
lineIndex = find(hChildren==associatedLine1);
% Reorder lines so the new line appears with associated data
hNewChildren = [hChildren(1:lineIndex-1);newLine1;hChildren(lineIndex:end)];
% Set the children:
set(axesh1,'Children',hNewChildren);

