function createfigure(X1, Y1,fe)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 05-Apr-2017 15:55:07

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create semilogx
semilogx(X1,Y1);

% Create xlabel
xlabel('f(Hz)');

% Create title
title(strcat('Spectre pour fe=',fe));

% Create ylabel
ylabel('Niveau (dB)');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XGrid','on','XMinorTick','on','XScale','log','YGrid','on');
